### ISSUE TITLE
pymusepipe not running with numpy 1.24.0

### ISSUE THREAD

**Issue by jusneuma** [emsellem/pymusepipe#10]
The newest version of numpy 1.24.0 has removed the command np.float(), therefore pymusepipe breaks with error:

`>>> from pymusepipe import musepipe
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
  File "/home/jneumann/pymusepipe/src/pymusepipe/__init__.py", line 11, in <module>
    from . import combine
  File "/home/jneumann/pymusepipe/src/pymusepipe/combine.py", line 35, in <module>
    from .recipes_pipe import PipeRecipes
  File "/home/jneumann/pymusepipe/src/pymusepipe/recipes_pipe.py", line 21, in <module>
    from . import util_pipe as upipe
  File "/home/jneumann/pymusepipe/src/pymusepipe/util_pipe.py", line 21, in <module>
    from .config_pipe import (default_filter_list, dict_musemodes,
  File "/home/jneumann/pymusepipe/src/pymusepipe/config_pipe.py", line 68, in <module>
    "DATE":  ['mjd', 'MJD-OBS', np.float, 'E'],
  File "/home/jneumann/anaconda3/musedr/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
`
Downgrading to version 1.23.0 solves the problem for now.

**Comment by emsellem** [comment]
Did remove all np.int and np.float to use in t and float
New version is 2.17.6 both on github and pip
